/**
 * Keyword index for App Guide help-center search.
 * Maps keywords to FAQ section numbers (1–21).
 */
export const SECTION_TITLES: Record<number, string> = {
  1: "What is the ATE Event App?",
  2: "How do I log in to the app?",
  3: "What happens the first time I log in?",
  4: "What information is required on my profile?",
  5: "How do I view my tickets?",
  6: "How do I assign a ticket from my quota?",
  7: "How do I transfer my personal ticket?",
  8: "How does networking work?",
  9: "How do connections work?",
  10: "How do meetings work?",
  11: "Do meeting requests expire?",
  12: "How do I request a meeting?",
  13: "Why can't I request meetings?",
  14: "How does QR code scanning work?",
  15: "How do I browse event sessions?",
  16: "What notifications will I receive?",
  17: "Why can't I access the main app?",
  18: "Why can't I transfer my ticket?",
  19: "Why didn't the recipient receive the ticket?",
  20: "I can't find my meeting request. Where is it?",
  21: "What are the most important things to remember?",
};

/** keyword (lowercase) -> section numbers */
export const KEYWORD_TO_SECTIONS: Record<string, number[]> = {
  ticket: [5, 6, 7, 13, 18, 19],
  tickets: [5, 6, 7, 13, 18, 19],
  "my ticket": [5, 6, 7],
  "personal ticket": [5, 6, 7],
  "assign ticket": [6, 18],
  "ticket assignment": [6],
  "ticket allocation": [6],
  "ticket transfer": [7, 18],
  "transfer ticket": [7, 18],
  "ticket recipient": [6, 7, 19],
  "ticket activation": [6, 7, 19],
  "ticket quota": [6, 7, 18],
  "quota tickets": [6, 7, 18],
  "available tickets": [5, 6, 18],
  "assigned tickets": [5, 6],
  "unassigned tickets": [5, 6],
  login: [2],
  "log in": [2],
  "sign in": [2],
  "access account": [2],
  "enter app": [2, 17],
  "verification code": [2],
  otp: [2],
  "one time password": [2],
  "email verification": [2],
  "6 digit code": [2],
  "verification email": [2],
  "login code": [2],
  authentication: [2],
  "app login": [2],
  profile: [4, 17],
  "edit profile": [4],
  "update profile": [4],
  "profile details": [4],
  "profile information": [4],
  "complete profile": [4, 17],
  "profile photo": [4],
  bio: [4],
  "job title": [4],
  company: [4],
  organisation: [4],
  country: [4],
  interests: [4],
  linkedin: [4],
  "linkedin url": [4],
  "linkedin username": [4],
  "profile visibility": [4],
  networking: [8, 9],
  attendees: [8],
  "attendee list": [8],
  "all attendees": [8],
  "recommended attendees": [8],
  "discover attendees": [8],
  connect: [8, 9],
  "connection request": [9],
  "accept connection": [9],
  "decline connection": [9],
  "remove connection": [9],
  "connections": [9],
  "professional networking": [8],
  meeting: [10, 11, 12, 13, 20],
  "request meeting": [12],
  "schedule meeting": [12],
  "meeting request": [10, 11, 12, 20],
  "meeting invite": [12],
  "meeting reason": [12],
  "meeting title": [12],
  "meeting link": [12],
  "virtual meeting": [12],
  "meeting time": [12],
  "meeting date": [12],
  "scheduled meetings": [10],
  "meeting requests": [10, 11, 12, 20],
  "inbound requests": [10],
  "outbound requests": [10],
  "accept meeting": [10],
  "reject meeting": [10],
  "meeting expiration": [11],
  "meeting expires": [11],
  "24 hour meeting": [11],
  "assign ticket to someone": [6],
  "ticket invitation": [6, 19],
  "accept ticket": [6, 7, 19],
  "ticket acceptance": [6, 7],
  "pending ticket": [6],
  "revoke ticket": [6],
  "revoke assignment": [6],
  "edit ticket assignment": [6],
  "transfer personal ticket": [7],
  "ticket transfer rules": [7],
  "transfer recipient": [7],
  "ticket ownership": [7],
  "irreversible transfer": [7],
  "lose event access": [7],
  "ticket holder": [7],
  scan: [14],
  "scan qr": [14],
  "scan ticket": [14],
  "qr code": [14],
  "qr scanner": [14],
  "scan attendee": [14],
  "scan profile": [14],
  "scan badge": [14],
  schedule: [15],
  "event schedule": [15],
  sessions: [15],
  "browse sessions": [15],
  "session list": [15],
  "session day": [15],
  "event agenda": [15],
  notifications: [16],
  "push notifications": [16],
  alerts: [16],
  "meeting notifications": [16],
  "connection notifications": [16],
  "ticket notifications": [16],
  "app alerts": [16],
  "cannot login": [2],
  "can't login": [2],
  "didn't receive code": [2],
  "no otp": [2],
  "code not received": [2],
  "verification failed": [2],
  "cannot transfer ticket": [7, 18],
  "can't transfer ticket": [7, 18],
  "transfer blocked": [18],
  "transfer unavailable": [18],
  "cannot assign ticket": [6],
  "can't assign ticket": [6],
  "recipient did not receive ticket": [19],
  "ticket not received": [19],
  "ticket invitation missing": [19],
  "cannot request meeting": [13],
  "can't request meeting": [13],
  "meeting disabled": [13],
  "meeting expired": [11],
  "meeting request expired": [11],
  "cannot access app": [17],
  "can't enter app": [17],
  "profile incomplete": [17],
  "cannot find meeting": [20],
  "meeting missing": [20],
  "meeting not showing": [20],
  menu: [5, 6, 7],
  "my tickets": [5],
  "scan tab": [5, 14],
  "attendees tab": [8],
  "connections tab": [9],
  "meetings tab": [10],
  "schedule tab": [15],
  "requests tab": [10],
  "inbound tab": [10],
  "outbound tab": [10],
  event: [1],
  expo: [1],
  "africa technology expo": [1],
  "ate event": [1],
  "ate app": [1],
  "event networking": [1],
  "event attendees": [8],
  help: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
  support: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
  faq: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
  guide: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
  "how to": [2, 3, 5, 6, 7, 8, 9, 10, 12, 14, 15],
  "how do i": [2, 3, 5, 6, 7, 8, 9, 10, 12, 14, 15],
  "where do i": [8, 20],
  "why can't i": [13, 17, 18],
};

/** Search keywords and return unique section numbers with titles */
export function searchGuide(query: string): { section: number; title: string }[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const seen = new Set<number>();
  const results: { section: number; title: string }[] = [];

  for (const [kw, sections] of Object.entries(KEYWORD_TO_SECTIONS)) {
    if (kw.includes(q) || q.split(/\s+/).every((w) => kw.includes(w))) {
      for (const s of sections) {
        if (!seen.has(s)) {
          seen.add(s);
          results.push({ section: s, title: SECTION_TITLES[s] || "" });
        }
      }
    }
  }
  results.sort((a, b) => a.section - b.section);
  return results;
}
