name: Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      deployments: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment: production
          initial-status: in_progress

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set image names
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          REPO=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_SHA=${REPO}:${SHORT_SHA}" >> $GITHUB_ENV
          echo "IMAGE_LATEST=${REPO}:latest" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_SHA }}
            ${{ env.IMAGE_LATEST }}

      - name: Deploy to Swarm via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 102.223.38.105
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u sparkafrica --password-stdin
            docker service update --image ${{ env.IMAGE_SHA }} --with-registry-auth \
            --env-add PORT=3000 \
            asf-deeplink_app

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: success
          environment-url: https://app.africastartupfestival.com

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: failure
